version: '3.6'
services:
  api:
    environment:
      - SENDING_ADDRESS
      - IRCC_RECEIVING_ADDRESS
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
    image: 'cdssnc/ircc-rescheduler-api:latest'
    labels:
      traefik.backend: api
      traefik.frontend.entryPoints: dev
      traefik.frontend.rule: 'PathPrefix:/graphql'
      traefik.port: '3001'
    ports:
      - '3001'
    volumes:
      - ./api:/app
  proxy:
    command: >
      --docker
      --entryPoints="Name:dev Address::3004"
    image: 'traefik:1.6'
    ports:
      - '3004:3004'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  web:
    image: 'cdssnc/ircc-rescheduler:latest'
    user: irccapp
    working_dir: /app
    environment:
      - RAZZLE_PUBLIC_DIR=/app/build/public
      - NODE_ENV=development
      - PORT=3004
    labels:
      traefik.backend: web
      traefik.dev.frontend.rule: 'PathPrefix:/'
      traefik.dev.frontend.entryPoints: dev
      traefik.dev.port: '3004'
    ports:
      - '3004'
      - '3005:3005'
    volumes:
      - ./web:/app:rw
    command: yarn dev
