module.exports = {
  id: 'calgary',
  email: 'cic-calgary-citizenship@cic.gc.ca',
  phone: '1-888-242-2100',
  receivingEmail: 'cic-calgary-citizenship@cic.gc.ca',
  recurring: {
    jan: ['tues', 'thurs'],
    feb: ['tues', 'thurs'],
    mar: ['tues', 'thurs'],
    apr: ['tues', 'thurs'],
    may: ['tues', 'thurs'],
    jun: ['tues', 'thurs'],
    jul: ['tues', 'thurs'],
    aug: ['tues', 'thurs'],
    sep: ['tues', 'thurs'],
    oct: ['tues', 'thurs'],
    nov: ['tues', 'thurs'],
    dec: ['tues', 'thurs'],
  },
}
